name: Publish Release Package
on:
  release:
    types:
      - published


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REF_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: true
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@garbee'
      - name: Install Deps
        run: npm ci
      - name: Make icons
        run: npm run make
      - name: Set version
        run: npm version --no-git-tag "$REF_NAME"
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}



