name: Update Icons
on:
  release:
    types:
      - published


jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: true
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@garbee'
      - name: Install Deps
        run: npm ci
      - name: Set to CommonJS for build
        run: npm pkg set 'type=commonjs'
      - name: Build
        run: npm run icons
      - name: Set to module for deploy
        run: npm pkg set 'type=module'
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}



